#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift 'lib'
require 'optparse'

options = {}
global = OptionParser.new do |opts|
  opts.on('--service-url URL', 'Connect to the host at this URL') do |url|
    options[:url] = url
  end
  opts.on('-h', '--help', 'Display this screen') do
    puts <<~HELP
      DESCRIPTION:
        The SDR Command Line Interface is a tool to interact with the Stanford Digital Repository.

      SYNOPSIS:
        sdr [options] <command>

      OPTIONS:
        --service-url (string)
        Override the command's default URL with the given URL.

        -h, --help
        Displays this screen

      COMMANDS
        deposit
        deposit files to the SDR

        login
        Will prompt for email & password and exchange it for an login token, which it saves in ~/.sdr/token

    HELP
    exit
  end
end

global.order!
command = ARGV.shift

subcommands = {
  'deposit' => OptionParser.new do |opts|
    opts.on('--label LABEL', 'The object label') do |label|
      options[:label] = label
    end
    opts.on('-h', '--help', 'Display this screen') do
      puts opts
      exit
    end
  end
}

unless subcommands.key?(command)
  puts "unknown command '#{command}'"
  exit
end

subcommands[command].order!

require 'repository_client'
options[:files] = ARGV unless ARGV.empty?
RepositoryClient::CLI.start(command, options)
